"""create users table

Revision ID: 260ac8d1826d
Revises: 1dd6a2b7ac28
Create Date: 2024-09-03 16:00:49.722641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '260ac8d1826d'
down_revision: Union[str, None] = '1dd6a2b7ac28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
